# Generated by Django 4.2.5 on 2023-11-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.IntegerField()),
                ('equipment_name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_equipmentbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField()),
                ('equipment_name', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
