# Generated by Django 4.2.5 on 2023-11-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_managers',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
