# Generated by Django 4.2.5 on 2023-11-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tbl_managers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_equipment',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
