# Generated by Django 4.2.5 on 2023-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tbl_equipment_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_truff_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truff_id', models.CharField(max_length=10)),
                ('truff_name', models.CharField(max_length=30)),
                ('booking_amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_turff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truff_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
