# Generated by Django 4.2.5 on 2023-12-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tbl_payment_tbl_truff_booking_tbl_turff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_turff',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
