# Generated by Django 4.2.5 on 2023-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tbl_turff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_truff_booking',
            name='user_id',
            field=models.CharField(default='www', max_length=100),
            preserve_default=False,
        ),
    ]
