# Generated by Django 4.2.5 on 2023-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tbl_truff_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_truff_booking',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
            preserve_default=False,
        ),
    ]
