# Generated by Django 4.2.5 on 2023-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tbl_truff_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_equipmentbooking',
            name='user_id',
            field=models.CharField(default=8129, max_length=10),
            preserve_default=False,
        ),
    ]
