# Generated by Django 4.2.5 on 2023-12-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tbl_equipmentbooking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_equipmentbooking',
            name='status',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
