# Generated by Django 4.0.4 on 2024-01-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_tbl_equipment_sales_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
            ],
        ),
    ]
