# Generated by Django 4.0.4 on 2024-01-03 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_login_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_managers',
            name='login_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.login_tb'),
        ),
    ]
