# Generated by Django 4.0.4 on 2024-01-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tbl_sales_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_tb',
            name='password',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login_tb',
            name='username',
            field=models.CharField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
